name: Build all base forgerock secure gateway components
run-name: Building a full release of sapig:'${{ inputs.release_version_number }}' 

on:
  workflow_dispatch:
    inputs:
      release_version_number:
        required: true
        type: string
      release_ref:
        required: true
        type: string
      java_version:
        required: false
        type: string
        default: '17'
      repository_url:
        required: true
        type: string

jobs:
  
  build_image_sapig:
    name: Build and deploy sapig
    uses: ./.github/workflows/build-and-push-sapig-to-aws.yml
    with:
      repository_url: 'SecureApiGateway/secure-api-gateway-ob-uk'
      release_version_number: ${{ inputs.release_version_number }}
      release_ref: ${{ inputs.release_ref }}
    secrets: inherit


  build_image_rcs:
      name: Build and deploy sapig
      uses: ./.github/workflows/build-and-push-rcs-to-aws.yml
      with:
        repository_url: 'SecureApiGateway/secure-api-gateway-ob-uk-rcs'
        release_version_number: ${{ inputs.release_version_number }}
        release_ref: ${{ inputs.release_ref }}
      secrets: inherit


  