name: build and push custom resource server image to gcp
run-name: Building resource server:'${{ inputs.release_version_number }}' 

on:
  workflow_call:
    inputs:
      release_version_number:
        required: true
        type: string
      release_ref:
        required: true
        type: string
      java_version:
        required: false
        type: string
        default: '17'
      repository_url:
          required: true
          type: string
  
  workflow_dispatch:
    inputs:
      release_version_number:
        required: true
        type: string
      release_ref:
        required: true
        type: string
      java_version:
        required: false
        type: string
        default: '17'
      repository_url:
          required: true
          type: string
          default: 'SecureApiGateway/secure-api-gateway-ob-uk-rs'

env: 
  IMAGE_ARTIFACT_NAME: "secure-api-gateway-rs"  
          

jobs:
  
  build_image:
    name: Build and deploy container image
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:

      # https://github.com/actions/checkout


      - name: Prepare JDK and Maven for build
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt' #adoptopenjdk
          java-version: ${{ inputs.java_version }}
          architecture: x64
          cache: 'maven'  

      - name: Checkout 
        run: |
          git clone -c http.extraHeader='Authorization: Bearer ${{ secrets.STASH_TOKEN }}' ${{ secrets.EXTERNAL_REPO_URL }} . 
      # Java version and maven settings with protected repository id
      
      - name: Pulling and configuring forgerock maven settings
        run: | 
          curl -u '${{ secrets.FORGEROCK_USER }}:${{ secrets.FORGEROCK_PASSWORD }}' https://maven.forgerock.org/artifactory/private-releases/settings.xml > settings.xml  
        
      - name: Building Jar
        run: mvn clean install -DskipTests -DskipITs -s settings.xml 
          
      - uses: 'google-github-actions/auth@v1.1.1'
        id: gcloud_auth
        with:
          credentials_json: ${{ secrets.GCR_CREDENTIALS_JSON }}

      - name: Set up Cloud SDK
        id: gcloud_sdk
        uses: 'google-github-actions/setup-gcloud@v1.1.1'

      - name: Set up docker auth
        id: gcloud_docker_auth
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev
    
      - name: Building and pushing Container Image
        run: |

          export GIT_SHA_SHORT=$(git rev-parse --short HEAD)
          cd secure-api-gateway-ob-uk-rs-server # needs a variable?
          docker build -f docker/Dockerfile --build-arg JAR_FILE=$(find  -maxdepth 2 -regex .*\.jar) -t ${{ secrets.GCP_REGISTRY }}/base/${{ env.IMAGE_ARTIFACT_NAME }}:${GIT_SHA_SHORT} .
          docker tag ${{ secrets.GCP_REGISTRY }}/base/${{ env.IMAGE_ARTIFACT_NAME }}:${GIT_SHA_SHORT} ${{ secrets.GCP_REGISTRY }}/base/${{ env.IMAGE_ARTIFACT_NAME }}:latest 
          docker push --all-tags ${{ secrets.GCP_REGISTRY }}/base/${{ env.IMAGE_ARTIFACT_NAME }}